### ISSUE TITLE
how to output error or text in worker process

### ISSUE THREAD

**Issue by ihorizons2022** [jonghwanhyeon/joblib-progress#5]
![image](https://github.com/jonghwanhyeon/joblib-progress/assets/121672603/e8dadcfc-f199-4792-bede-2f66f7cfc38b)
no output at all

**Comment by jonghwanhyeon** [comment]
<img width="685" alt="Printing numbers" src="https://github.com/jonghwanhyeon/joblib-progress/assets/1588996/f00ac5d9-2fea-4a6f-b873-c4e6bcb3dd9b">

It works on console in dirty way but I think it is not possible in Jupyter Notebook environment
